name 'iis'
maintainer 'Timothy Wright'
maintainer_email 'chef@eastbound.io'
license 'Apache-2.0'
description 'Installs/Configures all IIS features'
long_description 'Installs/Configures all IIS features'
version '0.1.1'
chef_version '>= 13.0'
